#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 11 19:21:32 2020

@author: amandanovak
"""

# Given a list of numbers and a number k, return whether any two numbers from the list add up to k.


def addK(list,k):
    if len(list) == 1:
        if list[0] == k:
            return True;
        else:
            return False;
    for x in range(0,len(list)-1):
        for y in range(1,len(list)):
            if x != y:
                if list[x] + list[y] == k:
                    return True;
    return False;
        
        

        
  